#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags
skip_tags: true

configuration: Debug

build:
  project:  Src\electrolyte.all.sln

